import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";import{getFirestore,collection,addDoc,query,orderBy,limit,onSnapshot,serverTimestamp,deleteDoc,doc}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";import{firebaseConfig,COLLECTION}from"../firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const $=s=>document.querySelector(s),loginBox=$('#loginBox'),appBox=$('#appBox'),msg=$('#loginMsg'),url=$('#url'),list=$('#list'),count=$('#count'),sync=$('#sync'),net=$('#net');let unsub=null;const QUEUE='pixora-admin-queue';
function online(){net.textContent=navigator.onLine?'Online':'Offline';net.style.background=navigator.onLine?'#e6f5ec':'#f1edf4';}addEventListener('online',online);addEventListener('offline',online);online();
function queueGet(){try{return JSON.parse(localStorage.getItem(QUEUE)||'[]')}catch{return[]}}function queueSet(x){localStorage.setItem(QUEUE,JSON.stringify(x))}
function safeText(value){return String(value??'')}
function makeItem(urlText,index){const item=document.createElement('div');item.className='item';const meta=document.createElement('div');meta.className='meta';const title=document.createElement('b');title.textContent='Waiting to sync';const u=document.createElement('div');u.className='url';u.textContent=safeText(urlText);meta.append(title,u);const btn=document.createElement('button');btn.className='delete';btn.textContent='Remove';btn.dataset.q=String(index);btn.onclick=()=>{const q=queueGet();q.splice(index,1);queueSet(q);renderQueue()};item.append(meta,btn);return item}
function renderQueue(){const box=$('#queue');box.replaceChildren();queueGet().forEach((x,i)=>box.appendChild(makeItem(x,i)))}
async function syncQueue(){if(!navigator.onLine||!auth.currentUser)return;let q=queueGet();if(!q.length)return;sync.textContent='Syncing offline items…';const left=[];for(const u of q){try{await addDoc(collection(db,COLLECTION),{imageUrl:u,createdAt:serverTimestamp()})}catch{left.push(u)}}queueSet(left);renderQueue();sync.textContent=left.length?'Some items are still waiting.':'All synced.'}
$('#login').onclick=async()=>{msg.textContent='Signing in…';try{await signInWithEmailAndPassword(auth,$('#email').value.trim(),$('#password').value);msg.textContent=''}catch(e){msg.textContent=e.code||'Sign-in failed'}};$('#logout').onclick=()=>signOut(auth);$('#form').onsubmit=async e=>{e.preventDefault();const u=url.value.trim();if(!/^https?:\/\//i.test(u))return;if(!navigator.onLine){const q=queueGet();q.push(u);queueSet(q);renderQueue();url.value='';sync.textContent='Saved locally; will sync when online.';return}try{await addDoc(collection(db,COLLECTION),{imageUrl:u,createdAt:serverTimestamp()});url.value='';sync.textContent='Image added.'}catch(e){sync.textContent='Could not add image; saved locally.';const q=queueGet();q.push(u);queueSet(q);renderQueue()}};
onAuthStateChanged(auth,user=>{if(unsub){unsub();unsub=null}if(!user){loginBox.hidden=false;appBox.hidden=true;return}loginBox.hidden=true;appBox.hidden=false;const q=query(collection(db,COLLECTION),orderBy('createdAt','desc'),limit(100));unsub=onSnapshot(q,s=>{count.textContent=`${s.size}${s.size===100?'+':''} images`;list.replaceChildren();s.docs.forEach(d=>{const x=d.data();const item=document.createElement('div');item.className='item';const img=document.createElement('img');img.loading='lazy';img.src=safeText(x.imageUrl);const meta=document.createElement('div');meta.className='meta';const title=document.createElement('b');title.textContent='Image';const u=document.createElement('div');u.className='url';u.textContent=safeText(x.imageUrl);meta.append(title,u);const btn=document.createElement('button');btn.className='delete';btn.dataset.id=d.id;btn.textContent='Delete';btn.onclick=async()=>{if(confirm('Delete this image?'))await deleteDoc(doc(db,COLLECTION,d.id))};item.append(img,meta,btn);list.appendChild(item)})},e=>{sync.textContent=e.code||'Firestore error'});renderQueue();syncQueue()});